CONFIG:
  PDS_ID: PDS249291
  VERSION: PDS_V1
  PDS_MODE: NORMAL

CAMERA:
  AWB_R: 
  AWB_B: 
  BRIGHTNESS: 120
  FOCUS_POSITION: 7.77

RPI:
  SHUTDOWN: true
  EXECUTION_HOURS: [8, 12, 16]

NETWORK:
  SSID: HiPoint
  PASW: Hi13160866poi
  PRIORITY: false
  NETWORK_THRES: 40
