CONFIG:
  PDS_ID: PDS000000
  VERSION: PDS_V1
  PDS_MODE: NORMAL

CAMERA:
  AWB_R: 2.21
  AWB_B: 1.88
  BRIGHTNESS: 120
  FOCUS_POSITION: 7.77

RPI:
  SHUTDOWN: True
  EXECUTION_HOURS: [8, 12, 16]

NETWORK:
  SSID: HiPoint
  PASW: Hi13160866poi
  PRIORITY: True
  NETWORK_THRES: 50
