CONFIG:
  PDS_ID: PDS249291
  VERSION: PDS_WIFI_V1
  PDS_MODE: N

CAMERA:
  AWB_R:
  AWB_B:
  BRIGHTNESS: 110
  FOCUS_POSITION:

RPI:
  SHUTDOWN: true
  EXECUTION_HOURS: [9, 13, 15]

NETWORK:
  SSID: HiPoint
  PASW: Hi13160866poi
  PRIORITY: false
  NETWORK_THRES: 40
